/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reservation = IDL.Record({
  'confirmationId' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllReservationsSortedByDateTime' : IDL.Func(
      [],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getAllReservationsSortedByGuestName' : IDL.Func(
      [],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  'makeReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reservation = IDL.Record({
    'confirmationId' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllReservationsSortedByDateTime' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getAllReservationsSortedByGuestName' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
    'makeReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };