/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ContactForm = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});
export const Reservation = IDL.Record({
  'confirmationId' : IDL.Nat,
  'date' : IDL.Text,
  'time' : IDL.Text,
  'guestName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'partySize' : IDL.Nat,
  'phoneNumber' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addMenuItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllReservationsSortedByDateTime' : IDL.Func(
      [],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getAllReservationsSortedByGuestName' : IDL.Func(
      [],
      [IDL.Vec(Reservation)],
      ['query'],
    ),
  'getContactFormById' : IDL.Func([IDL.Nat], [ContactForm], ['query']),
  'getMenuItemById' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  'makeReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ContactForm = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  const Reservation = IDL.Record({
    'confirmationId' : IDL.Nat,
    'date' : IDL.Text,
    'time' : IDL.Text,
    'guestName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'partySize' : IDL.Nat,
    'phoneNumber' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'addMenuItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllReservationsSortedByDateTime' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getAllReservationsSortedByGuestName' : IDL.Func(
        [],
        [IDL.Vec(Reservation)],
        ['query'],
      ),
    'getContactFormById' : IDL.Func([IDL.Nat], [ContactForm], ['query']),
    'getMenuItemById' : IDL.Func([IDL.Nat], [MenuItem], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
    'makeReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };