/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactForm {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'price' : number,
}
export interface Reservation {
  'confirmationId' : bigint,
  'date' : string,
  'time' : string,
  'guestName' : string,
  'notes' : [] | [string],
  'partySize' : bigint,
  'phoneNumber' : string,
}
export interface _SERVICE {
  'addMenuItem' : ActorMethod<[string, string, string, number], bigint>,
  'getAllContactForms' : ActorMethod<[], Array<ContactForm>>,
  'getAllReservationsSortedByDateTime' : ActorMethod<[], Array<Reservation>>,
  'getAllReservationsSortedByGuestName' : ActorMethod<[], Array<Reservation>>,
  'getContactFormById' : ActorMethod<[bigint], ContactForm>,
  'getMenuItemById' : ActorMethod<[bigint], MenuItem>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'getReservationById' : ActorMethod<[bigint], Reservation>,
  'makeReservation' : ActorMethod<
    [string, string, string, string, bigint, [] | [string]],
    bigint
  >,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];